# Generated by Django 4.2.2 on 2023-06-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipofutbol',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
